import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./Components/Navigation";
import { Container } from "@mui/material";
import './Styles/styles.scss'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <Container maxWidth="xl"  sx={{
            marginTop: {
              xs: '20%',  // mobile devices
              sm: '11%',  // tablets
              md: '9%',  // small desktops
              lg: '7%',  // medium desktops
              xl: '5%'   // large desktops
            }
          }}>{children}</Container>
      </body>
    </html>
  );
}
